apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitlab-allow-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{NAMESPACE}}
